# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-env-file

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The cdn.donmai.us nginx config
- name: danbooru-images-nginx-config
  namespace: danbooru
  files:
  - config/nginx.conf

# The danbooru.donmai.us nginx config
- name: danbooru-nginx-config
  namespace: danbooru
  files:
  - config/danbooru/nginx.conf

# The Downbooru nginx config for maintenance mode
- name: downbooru-nginx-config
  namespace: danbooru
  files:
  - config/downbooru/nginx.conf

# The betabooru.donmai.us .env config
- name: betabooru-config-env
  namespace: danbooru
  env: config/betabooru.env

# The danbooru.donmai.us .env config
- name: danbooru-config-env
  namespace: danbooru
  env: config/danbooru.env

- name: recommender-config-env
  namespace: danbooru
  env: config/recommender.env

- name: postgres-config
  namespace: danbooru
  files:
  - config/postgres/postgresql.conf
  - config/postgres/pg_hba.conf

- name: redis-config
  namespace: danbooru
  files:
  - config/redis/redis.conf

secretGenerator:
# The danbooru_local_config.rb for danbooru.donmai.us and betabooru.donmai.us
- name: danbooru-local-config
  namespace: danbooru
  files:
  - secrets/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru.donmai.us and betabooru.donmai.us secret .env config
- name: danbooru-secret-env
  namespace: danbooru
  env: secrets/danbooru.env

# The Fumimi Discord bot secret .env config
- name: fumimi-secret-env
  namespace: danbooru
  env: secrets/fumimi.env

# The Fumimi Discord bot secret .env config
- name: recommender-secret-env
  namespace: danbooru
  env: secrets/recommender.env

resources:
- namespaces.yaml
- ingress-nginx.yaml
- danbooru.yaml
- danbooru-images.yaml
- danbooru-cron.yaml
- danbooru-jobs.yaml
- betabooru.yaml
- downbooru.yaml
- postgres.yaml
- redis.yaml
- recommender.yaml
- iqdb.yaml
- fumimi.yaml
