# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-env-file

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The danbooru.donmai.us nginx config
- name: danbooru-nginx-config
  namespace: danbooru
  files:
  - config/danbooru/nginx.conf

# The Downbooru nginx config for maintenance mode
- name: downbooru-nginx-config
  namespace: danbooru
  files:
  - config/downbooru/nginx.conf

resources:
- namespaces.yaml
- danbooru.yaml
- danbooru-cron.yaml
- danbooru-jobs.yaml
- downbooru.yaml
