apiVersion: apps/v1
kind: Deployment
metadata:
  name: danbooru
spec:
  template:
    spec:
      nodeName: node1

      containers:
      - name: danbooru
        volumeMounts:
        - mountPath: /srv
          name: danbooru-images
          mountPropagation: HostToContainer

      volumes:
      - name: danbooru-images
        hostPath:
          path: /srv/images
