apiVersion: apps/v1
kind: Deployment
metadata:
  name: danbooru
spec:
  replicas: 3

  template:
    spec:
      nodeName: node1

      containers:
      - name: danbooru
        image: ghcr.io/danbooru/danbooru:testbooru
        volumeMounts:
        - mountPath: /srv
          name: danbooru-images
          mountPropagation: HostToContainer

      - name: openresty
        image: ghcr.io/danbooru/danbooru:testbooru

      volumes:
      - name: danbooru-images
        hostPath:
          path: /srv/images
