apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      nodeName: node1

      volumes:
      - name: postgres-data
        hostPath:
          path: /srv/postgres-14
