# vim: sw=2

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    shima.donmai.us:
      nginx_user: www-data
      nginx_site: danbooru.donmai.us
    saitou.donmai.us:
      nginx_user: www-data
      nginx_site: danbooru.donmai.us
    kagamihara.donmai.us:
      nginx_user: www-data
      nginx_site: danbooru.donmai.us
    kinako.donmai.us:
      nginx_user: nginx
      nginx_site: kinako.donmai.us
    oogaki.donmai.us:
    inuyama.donmai.us:
    oumae.donmai.us:
    yukinoshita.donmai.us:
    isshiki.donmai.us:
    naoko.donmai.us:
    # matomo.donmai.us:

  children:
    rails:
      hosts:
        shima.donmai.us:
        saitou.donmai.us:
        kagamihara.donmai.us:
        oogaki.donmai.us:
    nginx:
      hosts:
        shima.donmai.us:
        saitou.donmai.us:
        kagamihara.donmai.us:
        kinako.donmai.us:
    archives:
      hosts:
        oumae.donmai.us:
    reportbooru:
      hosts:
        isshiki.donmai.us:
