# vim: sw=2

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    kinako.donmai.us:
      nginx_user: nginx
      nginx_site: kinako.donmai.us
    oogaki.donmai.us:
    inuyama.donmai.us:
    oumae.donmai.us:
    yukinoshita.donmai.us:
    isshiki.donmai.us:
    naoko.donmai.us:
    korone.donmai.us:

  children:
    ovh:
      hosts:
        oogaki.donmai.us:
        korone.donmai.us:
    nginx:
      hosts:
        kinako.donmai.us:
    archives:
      hosts:
        oumae.donmai.us:
    reportbooru:
      hosts:
        isshiki.donmai.us:
