apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../kubernetes-dashboard
- ../cert-manager
- ../ingress-nginx
- ../danbooru-images

patches:
- path: patches/danbooru-images.yaml
  target:
    name: danbooru-images
    kind: Deployment
