apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deepdanbooru.yaml

configMapGenerator:
- name: deepdanbooru-config-env
  namespace: danbooru
  env: config/deepdanbooru.env
