# auth_debug = yes
mail_debug = yes
# verbose_ssl = yes

imap_client_workarounds = tb-extra-mailbox-sep
log_path = /dev/stdout
mail_location = maildir:/srv/opensmtpd/danbooru.donmai.us

namespace inbox {
  inbox = yes
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
}

protocols = imap
ssl = required
ssl_cert = </etc/dovecot/private/tls.crt
ssl_key =  </etc/dovecot/private/tls.key

userdb {
  args = uid=65534 gid=65534 home=/srv/opensmtpd
  driver = static
}

!include conf.d/*.conf
