dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3

# auth_debug = yes
mail_debug = yes
# verbose_ssl = yes

imap_client_workarounds = tb-extra-mailbox-sep
log_path = /dev/stdout
default_login_user = vmail
default_internal_user = vmail
default_internal_group = vmail

protocols = imap
ssl = required
ssl_server_cert_file = /etc/dovecot/private/tls.crt
ssl_server_key_file = /etc/dovecot/private/tls.key

namespace inbox {
  mail_driver = maildir
  mail_path = /srv/opensmtpd/danbooru.donmai.us

  inbox = yes
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
}

service imap-login {
  chroot =

  inet_listener imap {
    port = 0
  }
}

# service stats {
#   inet_listener http {
#     port = 9900
#   }
# }
#
# @metric_defaults = backend

userdb static {
  fields {
    uid = 65534
    gid = 65534
    home = /srv/opensmtpd
  }
}

!include conf.d/*.conf
