# Define a beta Danbooru instance running on betabooru.donmai.us.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: betabooru
  namespace: danbooru
  labels:
    app: betabooru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betabooru
  template:
    metadata:
      labels:
        app: betabooru
    spec:
      containers:
      - name: danbooru
        image: ghcr.io/danbooru/danbooru:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: betabooru-env
        volumeMounts:
        - name: betabooru-local-config
          mountPath: "/etc/danbooru"
          readOnly: true
      volumes:
      - name: betabooru-local-config
        secret:
          secretName: betabooru-local-config


---

apiVersion: v1
kind: Service
metadata:
  name: betabooru
  namespace: danbooru
spec:
  selector:
    app: betabooru
  ports:
    - port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: betabooru
  namespace: danbooru
spec:
  rules:
    - host: betabooru.donmai.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: betabooru
                port:
                  number: 80
  tls:
    - hosts:
      - betabooru.donmai.us
      secretName: donmai-us-tls
