# Define ingress and nginx server for serving static images files on cdn.donmai.us.

apiVersion: v1
kind: Namespace
metadata:
  name: danbooru

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: danbooru-images
  namespace: danbooru
  labels:
    app: danbooru-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danbooru-images

  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%

  template:
    metadata:
      labels:
        app: danbooru-images
    spec:
      containers:
      - name: nginx
        # https://hub.docker.com/r/openresty/openresty
        image: openresty/openresty:1.19.9.1-buster-fat
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: danbooru-images
          readOnly: true
          mountPropagation: HostToContainer
        - name: danbooru-images-nginx-config
          mountPath: "/usr/local/openresty/nginx/conf/nginx.conf"
          subPath: "nginx.conf"
          readOnly: true

        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        readinessProbe:
          httpGet:
            path: /images/download-preview.png
            port: 80
            httpHeaders:
            - name: Host
              value: cdn.donmai.us
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
          initialDelaySeconds: 2

        lifecycle:
          preStop: { exec: { command: ["sleep", "5"] }}

      volumes:
      - name: danbooru-images
        hostPath:
          path: /home/danbooru/images
      - name: danbooru-images-nginx-config
        configMap:
          name: danbooru-images-nginx-config
      nodeSelector:
        kubernetes.io/hostname: korone

---

apiVersion: v1
kind: Service
metadata:
  name: danbooru-images
  namespace: danbooru
spec:
  selector:
    app: danbooru-images
  ports:
    - port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danbooru-images
  namespace: danbooru
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "raikou1.donmai.us,raikou2.donmai.us,raikou3.donmai.us,raikou4.donmai.us"

spec:
  rules:
    - host: cdn.donmai.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danbooru-images
                port:
                  number: 80

  tls:
    - hosts:
      - cdn.donmai.us
      secretName: donmai-us-tls
