# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-env-file

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The cdn.donmai.us nginx config
- name: danbooru-images-nginx-config
  namespace: danbooru
  files:
  - config/nginx.conf

# The danbooru.donmai.us nginx config
- name: danbooru-nginx-config
  namespace: danbooru
  files:
  - config/danbooru/nginx.conf

# The Downbooru nginx config for maintenance mode
- name: downbooru-nginx-config
  namespace: danbooru
  files:
  - config/downbooru/nginx.conf

# The betabooru.donmai.us .env config
- name: betabooru-config-env
  namespace: danbooru
  env: config/betabooru.env

# The danbooru.donmai.us .env config
- name: danbooru-config-env
  namespace: danbooru
  env: config/danbooru.env

- name: postgres-config
  namespace: danbooru
  files:
  - config/postgres/postgresql.conf
  - config/postgres/pg_hba.conf

# The Prometheus config
- name: prometheus-config
  namespace: mgmt
  files:
  - config/prometheus/prometheus.yml

secretGenerator:
# The danbooru_local_config.rb for danbooru.donmai.us and betabooru.donmai.us
- name: danbooru-local-config
  namespace: danbooru
  files:
  - secrets/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru.donmai.us and betabooru.donmai.us secret .env config
- name: danbooru-secret-env
  namespace: danbooru
  env: secrets/danbooru.env

# The Fumimi Discord bot secret .env config
- name: fumimi-secret-env
  namespace: danbooru
  env: secrets/fumimi.env

# This Cloudflare API token is used by cert-manager to solve DNS01 challenges.
# This secret has to be in the cert-manager namespace for cert-manager to find
# it (see https://github.com/jetstack/cert-manager/issues/263). The hash suffix
# also has to be disabled so cert-manager can find it (see cluster-issuer.yaml).
- name: cloudflare-api-token
  namespace: cert-manager
  env: secrets/cloudflare-api-token.env
  options:
    disableNameSuffixHash: true

- name: pgadmin-env
  namespace: mgmt
  env: secrets/pgadmin.env

resources:
- cluster-issuer.yaml
- betabooru.yaml
- danbooru.yaml
- postgres-service.yaml
- redis-service.yaml
- recommender-service.yaml
- iqdb.yaml
- ingress-nginx.yaml
- danbooru-images.yaml
- certificate.yaml
- pgadmin.yaml
- kubernetes-dashboard.yaml
- danbooru-cron.yaml
- danbooru-jobs.yaml
- fumimi.yaml
- service-accounts.yaml
- downbooru.yaml
- namespaces.yaml
- prometheus.yaml
- prometheus-node-exporter.yaml
- postgres.yaml
