# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/#configmap-from-env-file

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: danbooru-images-nginx-config
  namespace: danbooru
  files:
  - config/nginx.conf
- name: danbooru-nginx-config
  namespace: danbooru
  files:
  - config/danbooru/nginx.conf
secretGenerator:
- name: betabooru-local-config
  namespace: danbooru
  files:
  - secrets/betabooru_local_config.rb
  - secrets/id_rsa
- name: betabooru-env
  namespace: danbooru
  env: secrets/betabooru.env

# This Cloudflare API token is used by cert-manager to solve DNS01 challenges.
# This secret has to be in the cert-manager namespace for cert-manager to find
# it (see https://github.com/jetstack/cert-manager/issues/263). The hash suffix
# also has to be disabled so cert-manager can find it (see cluster-issuer.yaml).
- name: cloudflare-api-token
  namespace: cert-manager
  env: secrets/cloudflare-api-token.env
  options:
    disableNameSuffixHash: true
- name: danbooru-local-config
  namespace: danbooru
  files:
  - secrets/danbooru_local_config.rb
  - secrets/id_rsa
- name: danbooru-env
  namespace: danbooru
  env: secrets/danbooru.env
- name: pgadmin-env
  env: secrets/pgadmin.env
resources:
- cluster-issuer.yaml
- betabooru.yaml
- danbooru.yaml
- postgres-service.yaml
- redis-service.yaml
- ingress-nginx.yaml
- danbooru-images.yaml
- certificate.yaml
- pgadmin.yaml
