apiVersion: v1
kind: Service
metadata:
  name: recommender
  namespace: danbooru
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: v1
kind: Endpoints
metadata:
  name: recommender
  namespace: danbooru
subsets:
- addresses:
  - ip: 172.16.0.3 # oogaki
  ports:
  - port: 5000
