# A service account for accessing the Kubernetes dashboard.
#
# https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
# https://kubernetes.io/docs/reference/access-authn-authz/authentication/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evazion
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evazion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: evazion
  namespace: kubernetes-dashboard

---

# A service account for deploying betabooru.donmai.us from Github Actions.
#
# To get the token:
#
#   kubectl -n danbooru get secret $(kubectl -n danbooru get sa/github-actions -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: danbooru

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: betabooru-deployer
  namespace: danbooru
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  resourceNames: ["betabooru"]
  verbs: ["get", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: betabooru-deployers
  namespace: danbooru
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: danbooru
roleRef:
  kind: Role
  name: betabooru-deployer
  apiGroup: rbac.authorization.k8s.io
