apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The cdn.donmai.us nginx config
- name: danbooru-images-nginx-config
  namespace: danbooru
  files:
  - config/nginx.conf

resources:
- danbooru-images.yaml
