apiVersion: apps/v1
kind: Deployment
metadata:
  name: danbooru-jobs
spec:
  replicas: 12

  template:
    spec:
      containers:
      - name: danbooru
        volumeMounts:
        - mountPath: /srv
          name: danbooru-images
          mountPropagation: HostToContainer

      volumes:
      - name: danbooru-images
        hostPath:
          path: /srv

      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: danbooru-jobs

      # Only run on the app servers.
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: kubernetes.io/hostname, operator: In, values: [gura, ame, ina] }
