kind: Deployment
metadata:
  name: danbooru-images
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: kubernetes.io/hostname, operator: In, values: [korone, kiara] }

      volumes:
      - name: danbooru-images
        hostPath:
          path: /home/danbooru/images
