apiVersion: apps/v1
kind: Deployment
metadata:
  name: danbooru
spec:
  replicas: 6

  template:
    spec:
      containers:
      - name: danbooru
        volumeMounts:
        - mountPath: /srv
          name: danbooru-images
          mountPropagation: HostToContainer

      # Try to run one instance per node. Avoid multiple instances on the same node
      # https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: danbooru

      volumes:
      - name: danbooru-images
        hostPath:
          path: /srv

      # Only run on the app servers.
      # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: kubernetes.io/hostname, operator: In, values: [gura, ame, ina] }
