apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensmtpd
spec:
  template:
    spec:
      nodeName: kiara

      volumes:
      - name: opensmtpd-data
        hostPath:
          path: /srv/opensmtpd
