apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebooru
spec:
  template:
    spec:
      volumes:
      - name: safebooru-secret-env
        secret:
          secretName: safebooru-secret-env
