apiVersion: apps/v1
kind: Deployment

metadata:
  name: fumimi
  namespace: danbooru
  labels:
    app: fumimi

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fumimi

  template:
    metadata:
      labels:
        app: fumimi

    spec:
      containers:
      - name: fumimi
        image: ghcr.io/danbooru/fumimi-discord:latest
        imagePullPolicy: Always

        envFrom:
        - secretRef:
            name: fumimi-secret-env
