apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: signoz
  labels:
    app: kube-state-metrics

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kube-state-metrics

  template:
    metadata:
      labels:
        app: kube-state-metrics

    spec:
      serviceAccountName: kube-state-metrics

      containers:
      - name: kube-state-metrics
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1
        imagePullPolicy: Always

        # XXX not supported in k8s 1.20: cronjobs, poddisruptionbudgets, horizontalpodautoscalers
        # XXX not useful: certificatesigningrequests, mutatingwebhookconfigurations, validatingwebhookconfigurations, volumeattachments, storageclasses, resourcequotas, replicationcontrollers, networkpolicies, namespaces, limitranges, ingresses, persistentvolumeclaims, persistentvolumes, leases
        args: [
          # "--resources", "certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments"
          "--resources", "configmaps,daemonsets,deployments,endpoints,jobs,nodes,pods,replicasets,secrets,services,statefulsets",
          "--metric-denylist", ".*_labels,.*_annotations"
        ]

        ports:
        - containerPort: 8080
        - containerPort: 8081

        readinessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 5
          initialDelaySeconds: 3

        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 3

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: signoz

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: signoz

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - serviceaccounts
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingressclasses
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - list
  - watch

---

apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: signoz
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
    - name: http-metrics
      port: 8080
    - name: internal-metrics
      port: 8081
