# https://devopscube.com/node-exporter-kubernetes/
# https://github.com/bibinwilson/kubernetes-node-exporter/blob/main/daemonset.yaml

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: signoz
  labels:
    app: node-exporter

spec:
  selector:
    matchLabels:
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter

    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.5.0
        args:
        - --path.rootfs=/host/root
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --no-collector.arp
        - --no-collector.dmi
        - --no-collector.entropy
        - --no-collector.nvme
        - --no-collector.os
        - --no-collector.uname
        - --no-collector.udp_queues
        - --no-collector.time
        - --no-collector.timex
        - --no-collector.textfile
        - --no-collector.softnet
        - --no-collector.schedstat
        - --no-collector.selinux
        - --no-collector.ipvs
        - --no-collector.infiniband
        - --collector.mountstats
        - --collector.tcpstat
        - --collector.processes
        - --collector.diskstats.device-exclude=^(loop|dm|sr|nvme\d+n\d+p\d+|sd[a-z][0-9])
        - --collector.filesystem.mount-points-exclude=^/(boot|dev|proc|run|sys|home|etc|var/)
        - --collector.filesystem.fs-types-exclude=fuse.sshfs|autofs
        - --collector.netclass.ignored-devices=^(veth|vlan|enx|enp.*np1|cni|docker|kube-ipvs|lo)
        - --collector.netdev.device-exclude=^(veth|vlan|enx|enp.*np1|cni|docker|kube-ipvs|lo)
        - --web.disable-exporter-metrics

        ports:
        - containerPort: 9100

        volumeMounts:
        - name: root
          mountPath: /host/root
          mountPropagation: HostToContainer
          readOnly: true
        - name: proc
          mountPath: /host/proc
          mountPropagation: HostToContainer
          readOnly: true
        - name: sys
          mountPath: /host/sys
          mountPropagation: HostToContainer
          readOnly: true

      hostNetwork: true
      hostPID: true

      volumes:
      - name: root
        hostPath:
          path: /
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys

---

kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: signoz
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"

spec:
  selector:
    app: node-exporter
  ports:
  - name: node-exporter
    port: 9100
