apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: signoz
  namespace: signoz
  labels:
    app: signoz

spec:
  replicas: 1
  serviceName: signoz

  selector:
    matchLabels:
      app: signoz

  template:
    metadata:
      labels:
        app: signoz

    spec:
      containers:
      - name: signoz
        image: signoz/signoz:v0.119.0
        imagePullPolicy: Always
        args: ["-config=/root/config/prometheus.yml"]

        ports:
        - containerPort: 8080
        - containerPort: 4320

        envFrom:
        - configMapRef:
            name: signoz-env
        - secretRef:
            name: signoz-secret-env

        volumeMounts:
        - name: signoz-config
          mountPath: /root/config
          readOnly: true
        - name: signoz-data
          mountPath: /var/lib/signoz
        - name: signoz-dashboards
          mountPath: /root/config/dashboards

        readinessProbe:
          httpGet:
            path: "/api/v1/health"
            port: 8080
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 5
          initialDelaySeconds: 3

        livenessProbe:
          httpGet:
            path: "/api/v1/health"
            port: 8080
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 4
          initialDelaySeconds: 3

      volumes:
      - name: signoz-config
        configMap:
          name: signoz-config
      # - name: signoz-data
      #   hostPath:
      #     path: /srv/signoz-signoz
      # - name: signoz-dashboards
      #   hostPath:
      #     path: /srv/signoz-dashboards

---

apiVersion: v1
kind: Service
metadata:
  name: signoz
  namespace: signoz
  labels:
    app: signoz
spec:
  selector:
    app: signoz
  ports:
    - name: http
      port: 8080
    - name: opamp-server
      port: 4320
