# Collects pull-based metrics.

receivers:
  otlp:
    protocols:
      grpc:
      http:
  redis:
    endpoint: "redis-svc.danbooru.svc.cluster.local:6379"
    collection_interval: 60s
  prometheus/internal:
    config:
      scrape_configs:
        # otel-collector-metrics internal metrics
        - job_name: otel-collector-metrics
          scrape_interval: 60s
          static_configs:
            - targets:
                - localhost:8888
              labels:
                job_name: otel-collector-metrics
#        # SigNoz span metrics
#        - job_name: signozspanmetrics-collector
#          scrape_interval: 60s
#          static_configs:
#            - targets:
#              - otel-collector.signoz.svc.cluster.local:8889

  prometheus/cloudflare:
    config:
      scrape_configs:
      - job_name: cloudflare-metrics
        scrape_interval: 60s
        static_configs:
        - targets:
          - cloudflare-exporter.signoz.svc.cluster.local:8080
          labels:
            job_name: cloudflare-metrics
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "^go_.*|^promhttp_.*|^process_.*"
          action: drop

  prometheus/postgres:
    config:
      scrape_configs:
      - job_name: postgres-metrics
        scrape_interval: 60s
        static_configs:
        - targets:
          - postgres-exporter.signoz.svc.cluster.local:9187
          labels:
            job_name: postgres-metrics
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "^go_.*|^promhttp_.*|^process_.*(max|fds).*|^pg_exporter.*|^pg_scrape.*|^postgres_exporter.*|^pg_stat_bgwriter_.*_total|^pg_database_size_bytes"
          action: drop

  prometheus/clickhouse:
    config:
      scrape_configs:
      - job_name: clickhouse-metrics
        scrape_interval: 60s
        static_configs:
        - targets:
          - clickhouse.signoz.svc.cluster.local:9363
          labels:
            job_name: clickhouse-metrics

  prometheus/squid:
    config:
      scrape_configs:
      - job_name: squid-metrics
        scrape_interval: 60s
        static_configs:
        - targets:
          - squid-exporter.signoz.svc.cluster.local:9301
          labels:
            job_name: squid-metrics

  prometheus/cert-manager:
    config:
      scrape_configs:
      - job_name: cert-manager-metrics
        scrape_interval: 60s
        static_configs:
        - targets:
          - cert-manager.cert-manager.svc.cluster.local:9402
          labels:
            job_name: cert-manager-metrics

  prometheus/node:
    config:
      scrape_configs:
      - job_name: node-metrics
        scrape_interval: 60s
        static_configs:
        - targets: ["172.16.0.7:9100"]
          labels:
            job_name: node-metrics
            node: ame
        - targets: ["172.16.0.8:9100"]
          labels:
            job_name: node-metrics
            node: gura
        - targets: ["172.16.0.9:9100"]
          labels:
            job_name: node-metrics
            node: ina
        - targets: ["172.16.0.10:9100"]
          labels:
            job_name: node-metrics
            node: mori
        - targets: ["172.16.0.11:9100"]
          labels:
            job_name: node-metrics
            node: kiara
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "^node_(cooling|cpu_guest|cpu_core_throttle|cpu_frequency_(max|min)|cpu_scaling_frequency_(max|min)|disk_info|exporter|filesystem_(device_error|free_bytes|readonly)|hwmon_(power|chip|sensor)|hwmon_temp_(min|max|crit|alarm)|netstat_(Icmp|Udp)|scrape|network_(up|carrier|address|device|dormant|flags|iface|info|mtu|name|net|protocol|speed)|sockstat_(FRAG|RAW|UDP)|zfs_(abd|arc_(arc|abd|access|anon|l2|hash|evict)|zil_zil_itx|vdev|fm|dnode|dmu|zpool_(state|dataset))).*"
          action: drop

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s

  memory_limiter:
    limit_mib: 2048 # 2GB
    spike_limit_mib: 512
    check_interval: 1s

  # Drop `country` label from certain metrics and reaggregate samples.
  metricstransform/cloudflare:
    transforms:
    - include: cloudflare_zone_requests_status_country_host|cloudflare_zone_firewall_events_count
      match_type: regexp
      action: update
      operations:
      - action: aggregate_labels
        label_set: ["action", "host", "source", "zone", "status"] # drop country label
        aggregation_type: sum

  metricstransform/node:
    transforms:
    # drop `cpu` label; sum cpus by mode
    - include: node_cpu_seconds_total
      match_type: regexp
      action: update
      operations:
      - action: aggregate_labels
        label_set: ["mode", "node"] # drop `cpu`
        aggregation_type: sum

    # drop `cpu` label; average frequencies
    - include: node_cpu_scaling_frequency_hertz
      match_type: regexp
      action: update
      operations:
      - action: aggregate_labels
        label_set: ["node"] # drop `cpu`
        aggregation_type: mean

    # drop `sensor` label; max temperatures by chip
    - include: node_hwmon_temp_celsius
      match_type: regexp
      action: update
      operations:
      - action: aggregate_labels
        label_set: ["chip", "node"] # drop `sensor`
        aggregation_type: max

  filter/cert-manager:
    metrics:
      include:
        match_type: strict
        metric_names:
          - certmanager_certificate_expiration_timestamp_seconds

  filter/squid:
    metrics:
      include:
        match_type: strict
        metric_names:
          - process_cpu_seconds_total
          - process_resident_memory_bytes
          - squid_DNS_Lookups_50
          - squid_DNS_Lookups_95
          - squid_HTTP_Requests_All_50
          - squid_HTTP_Requests_All_95
          - squid_client_http_kbytes_in_kbytes_total
          - squid_client_http_kbytes_out_kbytes_total
          - squid_client_http_requests_total
          - squid_client_http_errors_total
          - squid_server_all_kbytes_in_kbytes_total
          - squid_server_all_kbytes_out_kbytes_total
          - squid_server_all_requests_total
          - squid_server_all_errors_total
          - squid_up

  filter/clickhouse:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ClickHouseProfileEvents_Query
          - ClickHouseProfileEvents_SelectQuery
          - ClickHouseProfileEvents_InsertQuery
          - ClickHouseProfileEvents_AsyncInsertQuery
          - ClickHouseProfileEvents_AsyncInsertBytes
          - ClickHouseProfileEvents_FailedQuery
          - ClickHouseProfileEvents_FailedSelectQuery
          - ClickHouseProfileEvents_FailedInsertQuery
          - ClickHouseProfileEvents_FailedAsyncInsertQuery
          - ClickHouseProfileEvents_QueryTimeMicroseconds
          - ClickHouseProfileEvents_SelectQueryTimeMicroseconds
          - ClickHouseProfileEvents_InsertQueryTimeMicroseconds
          - ClickHouseProfileEvents_OtherQueryTimeMicroseconds
          - ClickHouseProfileEvents_FileOpen
          - ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead
          - ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes
          - ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite
          - ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes
          - ClickHouseProfileEvents_ReadCompressedBytes
          - ClickHouseProfileEvents_CompressedReadBufferBlocks
          - ClickHouseProfileEvents_CompressedReadBufferBytes
          - ClickHouseProfileEvents_MMappedFileCacheHits
          - ClickHouseProfileEvents_MMappedFileCacheMisses
          - ClickHouseProfileEvents_OpenedFileCacheHits
          - ClickHouseProfileEvents_OpenedFileCacheMisses
          - ClickHouseProfileEvents_IOBufferAllocs
          - ClickHouseProfileEvents_IOBufferAllocBytes
          - ClickHouseProfileEvents_ArenaAllocChunks
          - ClickHouseProfileEvents_ArenaAllocBytes
          - ClickHouseProfileEvents_FunctionExecute
          - ClickHouseProfileEvents_MarkCacheHits
          - ClickHouseProfileEvents_MarkCacheMisses
          - ClickHouseProfileEvents_QueryCacheHits
          - ClickHouseProfileEvents_QueryCacheMisses
          - ClickHouseProfileEvents_CreatedReadBufferOrdinary
          - ClickHouseProfileEvents_DiskReadElapsedMicroseconds
          - ClickHouseProfileEvents_DiskWriteElapsedMicroseconds
          - ClickHouseProfileEvents_NetworkReceiveElapsedMicroseconds
          - ClickHouseProfileEvents_NetworkSendElapsedMicroseconds
          - ClickHouseProfileEvents_NetworkReceiveBytes
          - ClickHouseProfileEvents_NetworkSendBytes
          - ClickHouseProfileEvents_InsertedRows
          - ClickHouseProfileEvents_InsertedBytes
          - ClickHouseProfileEvents_DelayedInserts
          - ClickHouseProfileEvents_RejectedInserts
          - ClickHouseProfileEvents_DelayedInsertsMilliseconds
          - ClickHouseProfileEvents_DuplicatedInsertedBlocks
          - ClickHouseProfileEvents_ZooKeeperTransactions
          - ClickHouseProfileEvents_ZooKeeperList
          - ClickHouseProfileEvents_ZooKeeperCreate
          - ClickHouseProfileEvents_ZooKeeperRemove
          - ClickHouseProfileEvents_ZooKeeperExists
          - ClickHouseProfileEvents_ZooKeeperGet
          - ClickHouseProfileEvents_ZooKeeperMulti
          - ClickHouseProfileEvents_ZooKeeperWatchResponse
          - ClickHouseProfileEvents_ZooKeeperWaitMicroseconds
          - ClickHouseProfileEvents_ZooKeeperBytesSent
          - ClickHouseProfileEvents_ZooKeeperBytesReceived
          - ClickHouseProfileEvents_ExternalProcessingCompressedBytesTotal
          - ClickHouseProfileEvents_ExternalProcessingUncompressedBytesTotal
          - ClickHouseProfileEvents_ExternalProcessingFilesTotal
          - ClickHouseProfileEvents_ExternalSortWritePart
          - ClickHouseProfileEvents_ExternalSortMerge
          - ClickHouseProfileEvents_ExternalSortCompressedBytes
          - ClickHouseProfileEvents_ExternalSortUncompressedBytes
          - ClickHouseProfileEvents_ExternalAggregationWritePart
          - ClickHouseProfileEvents_ExternalAggregationMerge
          - ClickHouseProfileEvents_ExternalAggregationCompressedBytes
          - ClickHouseProfileEvents_ExternalAggregationUncompressedBytes
          - ClickHouseProfileEvents_ExternalJoinWritePart
          - ClickHouseProfileEvents_ExternalJoinMerge
          - ClickHouseProfileEvents_ExternalJoinCompressedBytes
          - ClickHouseProfileEvents_ExternalJoinUncompressedBytes
          - ClickHouseProfileEvents_SelectedParts
          - ClickHouseProfileEvents_SelectedRanges
          - ClickHouseProfileEvents_SelectedMarks
          - ClickHouseProfileEvents_SelectedRows
          - ClickHouseProfileEvents_SelectedBytes
          - ClickHouseProfileEvents_WaitMarksLoadMicroseconds
          - ClickHouseProfileEvents_BackgroundLoadingMarksTasks
          - ClickHouseProfileEvents_Merge
          - ClickHouseProfileEvents_MergedRows
          - ClickHouseProfileEvents_MergedUncompressedBytes
          - ClickHouseProfileEvents_MergesTimeMilliseconds
          - ClickHouseProfileEvents_MergeTreeDataWriterRows
          - ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes
          - ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes
          - ClickHouseProfileEvents_MergeTreeDataWriterBlocks
          - ClickHouseProfileEvents_MergeTreeDataWriterBlocksAlreadySorted
          - ClickHouseProfileEvents_InsertedWideParts
          - ClickHouseProfileEvents_InsertedCompactParts
          - ClickHouseProfileEvents_InsertedInMemoryParts
          - ClickHouseProfileEvents_MergedIntoWideParts
          - ClickHouseProfileEvents_MergedIntoCompactParts
          - ClickHouseProfileEvents_MergedIntoInMemoryParts
          - ClickHouseProfileEvents_ContextLock
          - ClickHouseProfileEvents_RealTimeMicroseconds
          - ClickHouseProfileEvents_UserTimeMicroseconds
          - ClickHouseProfileEvents_SystemTimeMicroseconds
          - ClickHouseProfileEvents_SoftPageFaults
          - ClickHouseProfileEvents_HardPageFaults
          - ClickHouseProfileEvents_OSIOWaitMicroseconds
          - ClickHouseProfileEvents_OSCPUWaitMicroseconds
          - ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds
          - ClickHouseProfileEvents_OSReadBytes
          - ClickHouseProfileEvents_OSWriteBytes
          - ClickHouseProfileEvents_OSReadChars
          - ClickHouseProfileEvents_OSWriteChars
          - ClickHouseProfileEvents_QueryProfilerRuns
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheHit
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheHitBytes
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheHitElapsedMicroseconds
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheMiss
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheMissBytes
          - ClickHouseProfileEvents_ThreadPoolReaderPageCacheMissElapsedMicroseconds
          - ClickHouseProfileEvents_AsynchronousReadWaitMicroseconds
          - ClickHouseMetrics_TCPConnection
          - ClickHouseMetrics_MemoryTracking
          - ClickHouseMetrics_PartsActive
          - ClickHouseMetrics_PartsOutdated
          - ClickHouseMetrics_PartsWide
          - ClickHouseMetrics_PartsCompact
          - ClickHouseMetrics_PartsInMemory
          - ClickHouseMetrics_MMappedFileBytes
          - ClickHouseAsyncMetrics_MemoryResident
          - ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTables
          - ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTables
          - ClickHouseAsyncMetrics_TotalPartsOfMergeTreeTables
          - ClickHouseAsyncMetrics_NumberOfDetachedByUserParts
          - ClickHouseAsyncMetrics_NumberOfDetachedParts
          - ClickHouseAsyncMetrics_MarkCacheFiles
          - ClickHouseAsyncMetrics_MarkCacheBytes
          - ClickHouseAsyncMetrics_HashTableStatsCacheMisses
          - ClickHouseAsyncMetrics_HashTableStatsCacheEntries
          - ClickHouseAsyncMetrics_jemalloc_allocated
          - ClickHouseAsyncMetrics_jemalloc_metadata
          - ClickHouseAsyncMetrics_jemalloc_metadata_thp
          - ClickHouseAsyncMetrics_jemalloc_arenas_all_pmuzzy
          - ClickHouseAsyncMetrics_jemalloc_arenas_all_pactive
          - ClickHouseAsyncMetrics_jemalloc_background_thread_num_threads
          - ClickHouseAsyncMetrics_jemalloc_background_thread_num_runs
          - ClickHouseAsyncMetrics_jemalloc_arenas_all_muzzy_purged
          - ClickHouseAsyncMetrics_jemalloc_arenas_all_pdirty
          - ClickHouseAsyncMetrics_jemalloc_arenas_all_dirty_purged
          - ClickHouseAsyncMetrics_jemalloc_active
          - ClickHouseAsyncMetrics_jemalloc_retained
          - ClickHouseAsyncMetrics_jemalloc_mapped
          - ClickHouseAsyncMetrics_jemalloc_resident

#  transform/node:
#    metric_statements:
#    - context: metric
#      statements:
#      - drop() where IsMatch(metric.name, "^node_zfs_zpool_dataset") == true and IsMatch(attributes["dataset"], "zroot/data/var/") == true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: 0.0.0.0:55679
  pprof:
    endpoint: 0.0.0.0:1777

exporters:
  clickhousemetricswrite:
    endpoint: tcp://clickhouse.signoz.svc.cluster.local:9000/?database=signoz_metrics

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions:
    - health_check
    - zpages
    - pprof
  pipelines:
    metrics:
      receivers: [redis, prometheus/postgres, prometheus/internal]
      processors: [memory_limiter, batch]
      exporters: [clickhousemetricswrite]
    metrics/cloudflare:
      receivers: [prometheus/cloudflare]
      processors: [memory_limiter, metricstransform/cloudflare, batch]
      exporters: [clickhousemetricswrite]
    metrics/node:
      receivers: [prometheus/node]
      processors: [memory_limiter, metricstransform/node, batch]
      exporters: [clickhousemetricswrite]
    metrics/clickhouse:
      receivers: [prometheus/clickhouse]
      processors: [memory_limiter, filter/clickhouse, batch]
      exporters: [clickhousemetricswrite]
    metrics/squid:
      receivers: [prometheus/squid]
      processors: [memory_limiter, filter/squid, batch]
      exporters: [clickhousemetricswrite]
    metrics/cert-manager:
      receivers: [prometheus/cert-manager]
      processors: [memory_limiter, filter/cert-manager, batch]
      exporters: [clickhousemetricswrite]
