apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres.yaml

configMapGenerator:
- name: postgres-config
  namespace: danbooru
  files:
  - config/postgresql.conf
  - config/pg_hba.conf
