apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  namespace: elastic-apm
spec:
  storageClassName: local-storage
  capacity:
    storage: 15G
  accessModes:
  - ReadWriteOnce
  local:
    path: /host/srv/elasticsearch-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [node1]
