# A service account for deploying testbooru.donmai.us from Github Actions.
#
# To get the token:
#
#   kubectl --context testbooru -n danbooru get secret $(kubectl --context testbooru -n danbooru get sa/github-deployer -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer
  namespace: danbooru

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testbooru-deployer
  namespace: danbooru
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  # resourceNames: ["danbooru"]
  verbs: ["list", "watch", "get", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testbooru-deployers
  namespace: danbooru
subjects:
- kind: ServiceAccount
  name: github-deployer
  namespace: danbooru
roleRef:
  kind: Role
  name: testbooru-deployer
  apiGroup: rbac.authorization.k8s.io
