# vim: sw=2

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    oogaki.donmai.us:
    oumae.donmai.us:
    isshiki.donmai.us:
    naoko.donmai.us:
    ame.donmai.us:
    gura.donmai.us:
    ina.donmai.us:
    kiara.donmai.us:
    mori.donmai.us:
    irys.donmai.us:
    node1.haachama.donmai.us:
    node2.haachama.donmai.us:
    node3.haachama.donmai.us:

  children:
    k8s:
      hosts:
        ame.donmai.us:
        gura.donmai.us:
        ina.donmai.us:
        kiara.donmai.us:
        mori.donmai.us:
        irys.donmai.us:
        node1.haachama.donmai.us:
        node2.haachama.donmai.us:
        node3.haachama.donmai.us:
    ovh:
      hosts:
        oogaki.donmai.us:
    archives:
      hosts:
        oumae.donmai.us:
    reportbooru:
      hosts:
        isshiki.donmai.us:
