# vim: sw=2

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    oogaki.donmai.us:
    oumae.donmai.us:
    isshiki.donmai.us:
    naoko.donmai.us:

  children:
    ovh:
      hosts:
        oogaki.donmai.us:
    archives:
      hosts:
        oumae.donmai.us:
    reportbooru:
      hosts:
        isshiki.donmai.us:
