# vim: sw=2

- name: Update files in /etc/sysctl.d/
  hosts: k8s
  become: yes
  tags:
  - k8s
  tasks:
  - ansible.builtin.template:
      src: '{{ item.src }}'
      dest: '/etc/sysctl.d/{{ item.path | regex_replace("\.j2$", "") }}'
      owner: root
      group: root
      mode: '{{ item.mode }}'
    with_filetree: templates/etc/sysctl.d/
    when: item.state == 'file'
    notify:
    - Reload sysctl
  handlers:
  - name: Reload sysctl
    command: sysctl --system

- name: Update archives config
  hosts: archives
  become: yes
  become_user: archiver
  tags:
  - archives
  tasks:
  - name: Update .env
    template:
      src: templates/archives/env.j2
      dest: /var/www/archives/shared/.env

- name: Update reportbooru config
  hosts: reportbooru
  tags:
  - reportbooru
  tasks:
  - name: Update .env
    template:
      src: templates/reportbooru/env.j2
      dest: /var/www/reportbooru/shared/.env
