# vim: sw=2

- name: Update archives config
  hosts: archives
  become: yes
  become_user: archiver
  tags:
  - archives
  tasks:
  - name: Update .env
    template:
      src: templates/archives/env.j2
      dest: /var/www/archives/shared/.env

- name: Update reportbooru config
  hosts: reportbooru
  tags:
  - reportbooru
  tasks:
  - name: Update .env
    template:
      src: templates/reportbooru/env.j2
      dest: /var/www/reportbooru/shared/.env
