apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebooru
  namespace: danbooru
  labels:
    app: safebooru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safebooru
  template:
    metadata:
      labels:
        app: safebooru
    spec:
      hostname: safebooru
      containers:
      - name: danbooru
        image: ghcr.io/danbooru/danbooru:betabooru
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        envFrom:
        - configMapRef:
            name: safebooru-config-env
        - secretRef:
            name: danbooru-secret-env

        volumeMounts:
        - name: safebooru-local-config
          mountPath: "/etc/danbooru"
          readOnly: true

        # http://127.0.0.1:9293/stats is the Puma control endpoint. Note that this
        # endpoint will still respond even if Rails is unresponsive due to
        # being backlogged with slow requests.
        #
        # We use curl instead of httpGet because this endpoint is only listening
        # on localhost so the kubelet can't connect to it from outside.
        #
        # https://github.com/harmjanblok/puma-metrics
        readinessProbe:
          exec:
            command: ["curl", "http://127.0.0.1:9293/stats"]
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
          initialDelaySeconds: 5

      # See config/danbooru/nginx.conf for the nginx config.
      - name: openresty
        image: ghcr.io/danbooru/danbooru:betabooru
        imagePullPolicy: Always
        args: ["openresty", "-e", "/dev/stderr"]
        ports:
        - containerPort: 8080

        # Mount config/danbooru/nginx.conf at /usr/local/nginx/conf/nginx.conf
        volumeMounts:
        - name: danbooru-nginx-config
          mountPath: "/usr/local/nginx/conf"
          readOnly: true

        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        readinessProbe:
          httpGet:
            path: /nginx/status
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
          initialDelaySeconds: 5

      volumes:
      - name: safebooru-local-config
        secret:
          secretName: safebooru-local-config
      - name: danbooru-nginx-config
        configMap:
          name: danbooru-nginx-config
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: kubernetes.io/hostname, operator: In, values: [gura, ame, ina] }

---

apiVersion: v1
kind: Service
metadata:
  name: safebooru
  namespace: danbooru
spec:
  selector:
    app: safebooru
  ports:
    - port: 80
      targetPort: 8080
