apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The danbooru.donmai.us .env config
- name: danbooru-config-env
  namespace: danbooru
  env: config/danbooru.env

# The Prometheus config
- name: prometheus-config
  namespace: mgmt
  files:
  - config/prometheus/prometheus.yml

secretGenerator:
# The danbooru_local_config.rb for danbooru.donmai.us
- name: danbooru-local-config
  namespace: danbooru
  files:
  - secrets/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru_local_config.rb for betabooru.donmai.us
- name: betabooru-local-config
  namespace: danbooru
  files:
  - secrets/betabooru/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru.donmai.us and betabooru.donmai.us secret .env config
- name: danbooru-secret-env
  namespace: danbooru
  env: secrets/danbooru.env

- name: recommender-secret-env
  namespace: danbooru
  env: secrets/recommender.env

- name: fumimi-secret-env
  namespace: danbooru
  env: secrets/fumimi.env

- name: pgadmin-env
  namespace: mgmt
  env: secrets/pgadmin.env

resources:
- ../cert-manager
- ../kubernetes-dashboard
- ../ingress-nginx
- ../redis
- ../iqdb
- ../fumimi
- ../recommender
- ../postgres
- ../danbooru-images
- ../danbooru
- ../betabooru
- ../deepdanbooru
- namespaces.yaml
- service-accounts.yaml
- pgadmin.yaml
- prometheus.yaml
- prometheus-node-exporter.yaml
- ingresses.yaml

patches:
- path: patches/danbooru.yaml
  target:
    name: danbooru
    kind: Deployment
- path: patches/danbooru-cron.yaml
  target:
    name: danbooru-cron
    kind: Deployment
- path: patches/danbooru-jobs.yaml
  target:
    name: danbooru-jobs
    kind: Deployment
- path: patches/danbooru-images.yaml
  target:
    name: danbooru-images
    kind: Deployment
- path: patches/betabooru.yaml
  target:
    name: betabooru
    kind: Deployment
- path: patches/recommender.yaml
  target:
    name: recommender
    kind: Deployment
- path: patches/iqdb.yaml
  target:
    name: iqdb
    kind: Deployment
- path: patches/fumimi.yaml
  target:
    name: fumimi
    kind: Deployment
- path: patches/redis.yaml
  target:
    name: redis
    kind: StatefulSet
- path: patches/postgres.yaml
  target:
    name: postgres
    kind: StatefulSet
