apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# The danbooru.donmai.us .env config
- name: danbooru-config-env
  namespace: danbooru
  env: config/danbooru.env

# The Prometheus config
- name: prometheus-config
  namespace: mgmt
  files:
  - config/prometheus/prometheus.yml

# The OpenSMTPD config
- name: opensmtpd-config
  namespace: danbooru
  files:
  - config/opensmtpd/smtpd.conf

secretGenerator:
# The danbooru_local_config.rb for danbooru.donmai.us
- name: danbooru-local-config
  namespace: danbooru
  files:
  - secrets/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru_local_config.rb for betabooru.donmai.us
- name: betabooru-local-config
  namespace: danbooru
  files:
  - secrets/betabooru/danbooru_local_config.rb
  - secrets/id_rsa

# The danbooru.donmai.us and betabooru.donmai.us secret .env config
- name: danbooru-secret-env
  namespace: danbooru
  env: secrets/danbooru.env

- name: recommender-secret-env
  namespace: danbooru
  env: secrets/recommender.env

- name: fumimi-secret-env
  namespace: danbooru
  env: secrets/fumimi.env

- name: pgadmin-env
  namespace: mgmt
  env: secrets/pgadmin.env

- name: squid-config
  namespace: danbooru
  files:
  - secrets/squid/passwd
  - secrets/squid/squid.conf

- name: otel-collector-metrics-secret-env
  namespace: signoz
  env: secrets/signoz/otel-collector-metrics.env

- name: cloudflare-exporter-secret-env
  namespace: signoz
  env: secrets/signoz/cloudflare-exporter.env

- name: postgres-exporter-secret-env
  namespace: signoz
  env: secrets/signoz/postgres-exporter.env

- name: squid-exporter-secret-env
  namespace: signoz
  env: secrets/signoz/squid-exporter.env

resources:
- ../cert-manager
- ../kubernetes-dashboard
- ../ingress-nginx
- ../redis
- ../iqdb
- ../fumimi
- ../recommender
- ../postgres
- ../danbooru-images
- ../danbooru
- ../downbooru
- ../betabooru
- ../deepdanbooru
- ../autotagger
- ../elastic
- ../opensmtpd
- ../squid
- ../signoz
- namespaces.yaml
- service-accounts.yaml
- pgadmin.yaml
- prometheus.yaml
- ingresses.yaml
- local-storage.yaml
- elasticsearch-data.yaml

patches:
- path: patches/danbooru.yaml
  target:
    name: danbooru
    kind: Deployment
- path: patches/danbooru-cron.yaml
  target:
    name: danbooru-cron
    kind: Deployment
- path: patches/danbooru-jobs.yaml
  target:
    name: danbooru-jobs
    kind: Deployment
- path: patches/danbooru-images.yaml
  target:
    name: danbooru-images
    kind: Deployment
- path: patches/betabooru.yaml
  target:
    name: betabooru
    kind: Deployment
- path: patches/recommender.yaml
  target:
    name: recommender
    kind: Deployment
- path: patches/iqdb.yaml
  target:
    name: iqdb
    kind: Deployment
- path: patches/fumimi.yaml
  target:
    name: fumimi
    kind: Deployment
- path: patches/redis.yaml
  target:
    name: redis
    kind: StatefulSet
- path: patches/postgres.yaml
  target:
    name: postgres
    kind: StatefulSet
- path: patches/opensmtpd.yaml
  target:
    name: opensmtpd
    kind: StatefulSet
- path: patches/apm-server.yaml
  target:
    name: apm-server
    kind: Agent
- path: patches/kibana.yaml
  target:
    name: kibana
    kind: Kibana
- path: patches/zookeeper-signoz.yaml
  target:
    name: zookeeper
    namespace: signoz
    kind: StatefulSet
- path: patches/clickhouse-signoz.yaml
  target:
    name: clickhouse
    namespace: signoz
    kind: StatefulSet
- path: patches/query-service-signoz.yaml
  target:
    name: query-service
    namespace: signoz
    kind: StatefulSet
- path: patches/alertmanager-signoz.yaml
  target:
    name: alertmanager
    namespace: signoz
    kind: StatefulSet
