table domains { "donmai.us", "*.donmai.us", "donmai.moe", "*.donmai.moe" }
table aliases { "@" = "nobody" }

pki mail.donmai.us cert "/etc/opensmtpd/certificates/tls.crt"
pki mail.donmai.us key "/etc/opensmtpd/certificates/tls.key"

listen on 0.0.0.0 port 25 tls pki mail.donmai.us hostname mail.donmai.us
listen on 0.0.0.0 port 465 smtps pki mail.donmai.us hostname mail.donmai.us
listen on 0.0.0.0 port 587 tls-require pki mail.donmai.us hostname mail.donmai.us

action inbound maildir "/srv/opensmtpd/danbooru.donmai.us" virtual <aliases>
match from any for domain <domains> action inbound
