# https://docs.vagrantup.com
# https://learn.hashicorp.com/tutorials/vagrant/getting-started-index?in=vagrant/getting-started

Vagrant.configure("2") do |config|
  nodes = [
    { name: "node1", internal_ip: "172.16.0.2", external_ip: "65.21.78.102" },
    { name: "node2", internal_ip: "172.16.0.3", external_ip: "65.21.78.103" },
    { name: "node3", internal_ip: "172.16.0.4", external_ip: "65.21.78.104" },
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |config|
      config.vm.hostname = node[:name]

      # Ubuntu 20.10
      config.vm.box = "generic/ubuntu2010"

      # https://www.vagrantup.com/docs/networking/private_network
      # https://www.vagrantup.com/docs/providers/virtualbox/networking
      config.vm.network "public_network", ip: node[:external_ip]
      config.vm.network "private_network", ip: node[:internal_ip], libvirt__forward_mode: "none", virtualbox__intnet: true

      # https://www.vagrantup.com/docs/synced-folders/basic_usage
      config.vm.synced_folder ".", "/vagrant", disabled: true

      # https://www.vagrantup.com/docs/providers/virtualbox
      #config.vm.provider "virtualbox" do |v|
      #  v.name = node[:name]
      #  v.cpus = 4
      #  v.memory = 2048
      #
      #  # https://www.vagrantup.com/docs/providers/virtualbox/configuration#linked-clones
      #  v.linked_clone = true
      #
      #  # https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/guestadd-memory-usage.html
      #  #v.customize ["modifyvm", :id, "--pagefusion", "on"]
      #end

      config.vm.provider "libvirt" do |v|
        v.cpus = 6
        v.memory = 16384
      end

      config.vm.provision "shell", path: "./provision-vm.sh"
    end
  end
end
